Repository nextcloud-libraries/nextcloud-moment, pull requests merged in 2023-10, with the labels that each got.

#753 fix(l10n): check locale before applying seconds translation
  l10n/messages.pot
  lib/index.ts
Labels: bug, 3. to review

#655 chore: update workflows from templates
  .github/workflows/fixup.yml
Labels: dependencies, automated, 3. to review

#756 Release v1.2.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
